const GET_BOOKMARK_SONG_LIST = "goka/song/GET_BOOKMARK_SONG_LIST";
const UPDATE_BOOKMARK_SONG_SUCCESS = "goka/song/UPDATE_BOOKMARK_SONG_SUCCESS";
export default {
    GET_BOOKMARK_SONG_LIST,
    UPDATE_BOOKMARK_SONG_SUCCESS
};