const GET_NEARESTKARAOKIES = 'goka/nearestkaraokies/LOAD';
const GET_NEARESTKARAOKIES_SUCCESS = 'goka/nearestkaraokies/LOAD_SUCCESS';
const GET_NEARESTKARAOKIES_FAIL = 'goka/nearestkaraokies/LOAD_FAIL';
const SEARCH_LIST_KARAOKE = "goka/SEARCH_LIST_KARAOKE/LOAD";
const SEARCH_LIST_KARAOKE_SUCCESS = "goka/SEARCH_LIST_KARAOKE/LOAD_SUCCESS";
const SEARCH_LIST_KARAOKE_FAIL = "goka/SEARCH_LIST_KARAOKE/LOAD_FAIL";
const GET_CURRENT_LOCATION_SUCCESS = "goka/CURRENT_LOCATION_SUCCESS";
const GET_CURRENT_LOCATION_FAIL = "goka/GET_CURRENT_LOCATION_FAIL";
const UPDATE_SEARCH_QUERY = "goka/UPDATE_SEARCH_QUERY";
const UPDATE_SEARCH_TYPE = "goka/UPDATE_SEARCH_TYPE";
const GET_KARAOKIES = "goka/GET_KARAOKIES";
const UPDATE_NEAREST_PAGE = "goka/UPDATE_NEAREST_PAGE";

export default {
    GET_NEARESTKARAOKIES,
    GET_NEARESTKARAOKIES_SUCCESS,
    GET_NEARESTKARAOKIES_FAIL,
    SEARCH_LIST_KARAOKE,
    SEARCH_LIST_KARAOKE_SUCCESS,
    SEARCH_LIST_KARAOKE_FAIL,
    GET_CURRENT_LOCATION_SUCCESS,
    GET_CURRENT_LOCATION_FAIL,
    UPDATE_SEARCH_QUERY,
    UPDATE_SEARCH_TYPE,
    GET_KARAOKIES,
    UPDATE_NEAREST_PAGE
}
