const GET_SONG_LIST_SUCCESS = "goka/song/GET_SONG_LIST";
const SET_SEARCH_QUERY = "goka/song/SET_SEARCH_QUERY";
const UPDATE_FAV_SONG_SUCCESS = "goka/song/UPDATE_FAV_SONG_SUCCESS";
const UPDATE_PAGE = "goka/UPDATE_PAGE";

export default {
    GET_SONG_LIST_SUCCESS,
    SET_SEARCH_QUERY,
    UPDATE_FAV_SONG_SUCCESS,
    UPDATE_PAGE
};